linters:
  enable-all: true
  exclude-use-default: false
  disable:
    - execinquery
    - exhaustruct
    - exhaustivestruct
    - forbidigo
    - golint
    - interfacer
    - ireturn
    - maligned
    - paralleltest
    - scopelint
    - varnamelen

issues:
  exclude-use-default: false
  exclude:
    - 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked'

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    exclude-functions:
      - '(io.Closer).Close'
