version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - mage
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: rsc
    main: ./cmd/rsc
    binary: rsc
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - "-X github.com/dosquad/go-cliversion.GitRepo=https://github.com/na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitSlug=na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo=https://github.com/na4ma4/rsca"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: rsca
    main: ./cmd/rsca
    binary: rsca
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - "-X github.com/dosquad/go-cliversion.GitRepo=https://github.com/na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitSlug=na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo=https://github.com/na4ma4/rsca"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: rscad
    main: ./cmd/rscad
    binary: rscad
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - "-X github.com/dosquad/go-cliversion.GitRepo=https://github.com/na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitSlug=na4ma4/rsca"
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo=https://github.com/na4ma4/rsca"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64']

archives:
  - allow_different_binary_count: true

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: rsca
    package_name: rsca
    file_name_template: "rsca_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    ids:
      - rsca
    homepage: https://github.com/na4ma4/rsca
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Remote service check agent (agent)
    formats:
      - apk
      - deb
    bindir: /usr/sbin
    contents:
      - src: "systemd/client/rsca.service"
        dst: "/lib/systemd/system/rsca.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/client/pre-install.sh"
          postinstall: "nfpms/client/post-install.sh"
          preremove: "nfpms/client/pre-remove.sh"
          postremove: "nfpms/client/post-remove.sh"
  -
    id: rscad
    package_name: rscad
    file_name_template: "rscad_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    ids:
      - rscad
    homepage: https://github.com/na4ma4/rsca
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Remote service check agent (server)
    formats:
      - apk
      - deb
    bindir: /usr/sbin
    contents:
      - src: "systemd/server/rscad.service"
        dst: "/lib/systemd/system/rscad.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/server/pre-install.sh"
          postinstall: "nfpms/server/post-install.sh"
          preremove: "nfpms/server/pre-remove.sh"
          postremove: "nfpms/server/post-remove.sh"

homebrew_casks:
  -
    name: rsc
    repository:
      owner: na4ma4
      name: homebrew-tap
    ids:
      - rsc
    binary: rsc
    commit_author:
      name: goreleaserbot
      email: na4ma4@users.noreply.github.com
    directory: Formula
    homepage: https://github.com/na4ma4/rsca
    description: Remote service check agent (client)
    hooks:
      post:
        # replace foo with the actual binary name
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rsc"]
          end
