env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: rsc
    main: ./cmd/rsc
    binary: rsc
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64

  - id: rsca
    main: ./cmd/rsca
    binary: rsca
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64

  - id: rscad
    main: ./cmd/rscad
    binary: rscad
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64

archives:

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: rsca
    package_name: rsca
    file_name_template: "rsca_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - rsca
    homepage: https://github.com/na4ma4/rsca
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Remote service check agent (agent)
    formats:
      - apk
      - deb
    bindir: /usr/sbin
    contents:
      - src: "systemd/client/rsca.service"
        dst: "/lib/systemd/system/rsca.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/client/pre-install.sh"
          postinstall: "nfpms/client/post-install.sh"
          preremove: "nfpms/client/pre-remove.sh"
          postremove: "nfpms/client/post-remove.sh"
  -
    id: rscad
    package_name: rscad
    file_name_template: "rscad_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - rscad
    homepage: https://github.com/na4ma4/rsca
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Remote service check agent (server)
    formats:
      - apk
      - deb
    bindir: /usr/sbin
    contents:
      - src: "systemd/server/rscad.service"
        dst: "/lib/systemd/system/rscad.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/server/pre-install.sh"
          postinstall: "nfpms/server/post-install.sh"
          preremove: "nfpms/server/pre-remove.sh"
          postremove: "nfpms/server/post-remove.sh"

brews:
  -
    name: rsc
    tap:
      owner: na4ma4
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: na4ma4@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/na4ma4/rsca
    description: Remote service check agent (client)
    test: |
      system "#{bin}/rsc --version"
    install: |
      bin.install "rsc"
