// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: github.com/na4ma4/rsca/api/admin.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveHostRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveHostRequest) Reset() {
	*x = RemoveHostRequest{}
	mi := &file_github_com_na4ma4_rsca_api_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostRequest) ProtoMessage() {}

func (x *RemoveHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveHostRequest) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *RemoveHostRequest) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type RemoveHostRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 RemoveHostRequest_builder) Build() *RemoveHostRequest {
	m0 := &RemoveHostRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

type RemoveHostResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveHostResponse) Reset() {
	*x = RemoveHostResponse{}
	mi := &file_github_com_na4ma4_rsca_api_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHostResponse) ProtoMessage() {}

func (x *RemoveHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveHostResponse) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *RemoveHostResponse) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type RemoveHostResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 RemoveHostResponse_builder) Build() *RemoveHostResponse {
	m0 := &RemoveHostResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

var File_github_com_na4ma4_rsca_api_admin_proto protoreflect.FileDescriptor

const file_github_com_na4ma4_rsca_api_admin_proto_rawDesc = "" +
	"\n" +
	"&github.com/na4ma4/rsca/api/admin.proto\x12\brsca.api\x1a!google/protobuf/go_features.proto\x1a'github.com/na4ma4/rsca/api/common.proto\")\n" +
	"\x11RemoveHostRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"*\n" +
	"\x12RemoveHostResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names2\x82\x02\n" +
	"\x05Admin\x120\n" +
	"\tListHosts\x12\x0f.rsca.api.Empty\x1a\x10.rsca.api.Member0\x01\x12G\n" +
	"\n" +
	"RemoveHost\x12\x1b.rsca.api.RemoveHostRequest\x1a\x1c.rsca.api.RemoveHostResponse\x12=\n" +
	"\n" +
	"TriggerAll\x12\x11.rsca.api.Members\x1a\x1c.rsca.api.TriggerAllResponse\x12?\n" +
	"\vTriggerInfo\x12\x11.rsca.api.Members\x1a\x1d.rsca.api.TriggerInfoResponseB$Z\x1agithub.com/na4ma4/rsca/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_github_com_na4ma4_rsca_api_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_na4ma4_rsca_api_admin_proto_goTypes = []any{
	(*RemoveHostRequest)(nil),   // 0: rsca.api.RemoveHostRequest
	(*RemoveHostResponse)(nil),  // 1: rsca.api.RemoveHostResponse
	(*Empty)(nil),               // 2: rsca.api.Empty
	(*Members)(nil),             // 3: rsca.api.Members
	(*Member)(nil),              // 4: rsca.api.Member
	(*TriggerAllResponse)(nil),  // 5: rsca.api.TriggerAllResponse
	(*TriggerInfoResponse)(nil), // 6: rsca.api.TriggerInfoResponse
}
var file_github_com_na4ma4_rsca_api_admin_proto_depIdxs = []int32{
	2, // 0: rsca.api.Admin.ListHosts:input_type -> rsca.api.Empty
	0, // 1: rsca.api.Admin.RemoveHost:input_type -> rsca.api.RemoveHostRequest
	3, // 2: rsca.api.Admin.TriggerAll:input_type -> rsca.api.Members
	3, // 3: rsca.api.Admin.TriggerInfo:input_type -> rsca.api.Members
	4, // 4: rsca.api.Admin.ListHosts:output_type -> rsca.api.Member
	1, // 5: rsca.api.Admin.RemoveHost:output_type -> rsca.api.RemoveHostResponse
	5, // 6: rsca.api.Admin.TriggerAll:output_type -> rsca.api.TriggerAllResponse
	6, // 7: rsca.api.Admin.TriggerInfo:output_type -> rsca.api.TriggerInfoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_na4ma4_rsca_api_admin_proto_init() }
func file_github_com_na4ma4_rsca_api_admin_proto_init() {
	if File_github_com_na4ma4_rsca_api_admin_proto != nil {
		return
	}
	file_github_com_na4ma4_rsca_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_na4ma4_rsca_api_admin_proto_rawDesc), len(file_github_com_na4ma4_rsca_api_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_na4ma4_rsca_api_admin_proto_goTypes,
		DependencyIndexes: file_github_com_na4ma4_rsca_api_admin_proto_depIdxs,
		MessageInfos:      file_github_com_na4ma4_rsca_api_admin_proto_msgTypes,
	}.Build()
	File_github_com_na4ma4_rsca_api_admin_proto = out.File
	file_github_com_na4ma4_rsca_api_admin_proto_goTypes = nil
	file_github_com_na4ma4_rsca_api_admin_proto_depIdxs = nil
}
