// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: github.com/na4ma4/rsca/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_github_com_na4ma4_rsca_api_api_proto protoreflect.FileDescriptor

const file_github_com_na4ma4_rsca_api_api_proto_rawDesc = "" +
	"\n" +
	"$github.com/na4ma4/rsca/api/api.proto\x12\brsca.api\x1a!google/protobuf/go_features.proto\x1a'github.com/na4ma4/rsca/api/common.proto28\n" +
	"\x04RSCA\x120\n" +
	"\x04Pipe\x12\x11.rsca.api.Message\x1a\x11.rsca.api.Message(\x010\x01B$Z\x1agithub.com/na4ma4/rsca/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_github_com_na4ma4_rsca_api_api_proto_goTypes = []any{
	(*Message)(nil), // 0: rsca.api.Message
}
var file_github_com_na4ma4_rsca_api_api_proto_depIdxs = []int32{
	0, // 0: rsca.api.RSCA.Pipe:input_type -> rsca.api.Message
	0, // 1: rsca.api.RSCA.Pipe:output_type -> rsca.api.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_na4ma4_rsca_api_api_proto_init() }
func file_github_com_na4ma4_rsca_api_api_proto_init() {
	if File_github_com_na4ma4_rsca_api_api_proto != nil {
		return
	}
	file_github_com_na4ma4_rsca_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_na4ma4_rsca_api_api_proto_rawDesc), len(file_github_com_na4ma4_rsca_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_na4ma4_rsca_api_api_proto_goTypes,
		DependencyIndexes: file_github_com_na4ma4_rsca_api_api_proto_depIdxs,
	}.Build()
	File_github_com_na4ma4_rsca_api_api_proto = out.File
	file_github_com_na4ma4_rsca_api_api_proto_goTypes = nil
	file_github_com_na4ma4_rsca_api_api_proto_depIdxs = nil
}
