// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: github.com/na4ma4/rsca/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RSCA_Pipe_FullMethodName = "/rsca.api.RSCA/Pipe"
)

// RSCAClient is the client API for RSCA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RSCAClient interface {
	Pipe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type rSCAClient struct {
	cc grpc.ClientConnInterface
}

func NewRSCAClient(cc grpc.ClientConnInterface) RSCAClient {
	return &rSCAClient{cc}
}

func (c *rSCAClient) Pipe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RSCA_ServiceDesc.Streams[0], RSCA_Pipe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RSCA_PipeClient = grpc.BidiStreamingClient[Message, Message]

// RSCAServer is the server API for RSCA service.
// All implementations should embed UnimplementedRSCAServer
// for forward compatibility.
type RSCAServer interface {
	Pipe(grpc.BidiStreamingServer[Message, Message]) error
}

// UnimplementedRSCAServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRSCAServer struct{}

func (UnimplementedRSCAServer) Pipe(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method Pipe not implemented")
}
func (UnimplementedRSCAServer) testEmbeddedByValue() {}

// UnsafeRSCAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RSCAServer will
// result in compilation errors.
type UnsafeRSCAServer interface {
	mustEmbedUnimplementedRSCAServer()
}

func RegisterRSCAServer(s grpc.ServiceRegistrar, srv RSCAServer) {
	// If the following call pancis, it indicates UnimplementedRSCAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RSCA_ServiceDesc, srv)
}

func _RSCA_Pipe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RSCAServer).Pipe(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RSCA_PipeServer = grpc.BidiStreamingServer[Message, Message]

// RSCA_ServiceDesc is the grpc.ServiceDesc for RSCA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RSCA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsca.api.RSCA",
	HandlerType: (*RSCAServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pipe",
			Handler:       _RSCA_Pipe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/na4ma4/rsca/api/api.proto",
}
