// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: github.com/na4ma4/rsca/api/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK       Status = 0
	Status_WARNING  Status = 1
	Status_CRITICAL Status = 2
	Status_UNKNOWN  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "WARNING",
		2: "CRITICAL",
		3: "UNKNOWN",
	}
	Status_value = map[string]int32{
		"OK":       0,
		"WARNING":  1,
		"CRITICAL": 2,
		"UNKNOWN":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_na4ma4_rsca_api_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_github_com_na4ma4_rsca_api_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{0}
}

type CheckType int32

const (
	CheckType_HOST    CheckType = 0
	CheckType_SERVICE CheckType = 1
)

// Enum value maps for CheckType.
var (
	CheckType_name = map[int32]string{
		0: "HOST",
		1: "SERVICE",
	}
	CheckType_value = map[string]int32{
		"HOST":    0,
		"SERVICE": 1,
	}
)

func (x CheckType) Enum() *CheckType {
	p := new(CheckType)
	*p = x
	return p
}

func (x CheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_na4ma4_rsca_api_common_proto_enumTypes[1].Descriptor()
}

func (CheckType) Type() protoreflect.EnumType {
	return &file_github_com_na4ma4_rsca_api_common_proto_enumTypes[1]
}

func (x CheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckType.Descriptor instead.
func (CheckType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{0}
}

type TriggerAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *TriggerAllResponse) Reset() {
	*x = TriggerAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAllResponse) ProtoMessage() {}

func (x *TriggerAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAllResponse.ProtoReflect.Descriptor instead.
func (*TriggerAllResponse) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerAllResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type TriggerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *TriggerInfoResponse) Reset() {
	*x = TriggerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerInfoResponse) ProtoMessage() {}

func (x *TriggerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerInfoResponse.ProtoReflect.Descriptor instead.
func (*TriggerInfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerInfoResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender    *Member  `protobuf:"bytes,10,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient *Members `protobuf:"bytes,11,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetSender() *Member {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Envelope) GetRecipient() *Members {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type Members struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         []string `protobuf:"bytes,10,rep,name=id,proto3" json:"id,omitempty"`
	Name       []string `protobuf:"bytes,11,rep,name=name,proto3" json:"name,omitempty"`
	Capability []string `protobuf:"bytes,12,rep,name=capability,proto3" json:"capability,omitempty"`
	Tag        []string `protobuf:"bytes,13,rep,name=tag,proto3" json:"tag,omitempty"`
	Service    []string `protobuf:"bytes,14,rep,name=service,proto3" json:"service,omitempty"`
}

func (x *Members) Reset() {
	*x = Members{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Members) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Members) ProtoMessage() {}

func (x *Members) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Members.ProtoReflect.Descriptor instead.
func (*Members) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{4}
}

func (x *Members) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Members) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Members) GetCapability() []string {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *Members) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Members) GetService() []string {
	if x != nil {
		return x.Service
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InternalId   string                 `protobuf:"bytes,2,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	Name         string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Capability   []string               `protobuf:"bytes,11,rep,name=capability,proto3" json:"capability,omitempty"`
	Tag          []string               `protobuf:"bytes,12,rep,name=tag,proto3" json:"tag,omitempty"`
	Service      []string               `protobuf:"bytes,13,rep,name=service,proto3" json:"service,omitempty"`
	Version      string                 `protobuf:"bytes,90,opt,name=version,proto3" json:"version,omitempty"`
	GitHash      string                 `protobuf:"bytes,91,opt,name=git_hash,json=gitHash,proto3" json:"git_hash,omitempty"`
	BuildDate    string                 `protobuf:"bytes,92,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	LastSeen     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	PingLatency  *durationpb.Duration   `protobuf:"bytes,102,opt,name=ping_latency,json=pingLatency,proto3" json:"ping_latency,omitempty"`
	InfoStat     *InfoStat              `protobuf:"bytes,200,opt,name=info_stat,json=infoStat,proto3" json:"info_stat,omitempty"`
	SystemStart  *timestamppb.Timestamp `protobuf:"bytes,201,opt,name=system_start,json=systemStart,proto3" json:"system_start,omitempty"`
	ProcessStart *timestamppb.Timestamp `protobuf:"bytes,202,opt,name=process_start,json=processStart,proto3" json:"process_start,omitempty"`
	// Only used in rendering host lists, not transferred over the wire.
	LastSeenAgo string `protobuf:"bytes,1001,opt,name=last_seen_ago,json=lastSeenAgo,proto3" json:"last_seen_ago,omitempty"`
	Latency     string `protobuf:"bytes,1003,opt,name=latency,proto3" json:"latency,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{5}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetCapability() []string {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *Member) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Member) GetService() []string {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Member) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Member) GetGitHash() string {
	if x != nil {
		return x.GitHash
	}
	return ""
}

func (x *Member) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *Member) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Member) GetPingLatency() *durationpb.Duration {
	if x != nil {
		return x.PingLatency
	}
	return nil
}

func (x *Member) GetInfoStat() *InfoStat {
	if x != nil {
		return x.InfoStat
	}
	return nil
}

func (x *Member) GetSystemStart() *timestamppb.Timestamp {
	if x != nil {
		return x.SystemStart
	}
	return nil
}

func (x *Member) GetProcessStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessStart
	}
	return nil
}

func (x *Member) GetLastSeenAgo() string {
	if x != nil {
		return x.LastSeenAgo
	}
	return ""
}

func (x *Member) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

type InfoStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hostname  string                 `protobuf:"bytes,21,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime    uint64                 `protobuf:"varint,22,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BootTime  uint64                 `protobuf:"varint,23,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	// number of processes
	Procs uint64 `protobuf:"varint,24,opt,name=procs,proto3" json:"procs,omitempty"`
	// ex: freebsd, linux
	Os string `protobuf:"bytes,25,opt,name=os,proto3" json:"os,omitempty"`
	// ex: ubuntu, linuxmint
	Platform string `protobuf:"bytes,26,opt,name=platform,proto3" json:"platform,omitempty"`
	// ex: debian, rhel
	PlatformFamily string `protobuf:"bytes,27,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`
	// version of the complete OS
	PlatformVersion string `protobuf:"bytes,28,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	// version of the OS kernel (if available)
	KernelVersion string `protobuf:"bytes,29,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// native cpu architecture queried at runtime, as returned by `uname -m` or empty string in case of error
	KernelArch string `protobuf:"bytes,30,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	VirtSystem string `protobuf:"bytes,31,opt,name=virt_system,json=virtSystem,proto3" json:"virt_system,omitempty"`
	// guest or host
	VirtRole string `protobuf:"bytes,32,opt,name=virt_role,json=virtRole,proto3" json:"virt_role,omitempty"`
	// ex: uuid
	HostId string `protobuf:"bytes,33,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *InfoStat) Reset() {
	*x = InfoStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoStat) ProtoMessage() {}

func (x *InfoStat) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoStat.ProtoReflect.Descriptor instead.
func (*InfoStat) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{6}
}

func (x *InfoStat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *InfoStat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InfoStat) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *InfoStat) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *InfoStat) GetProcs() uint64 {
	if x != nil {
		return x.Procs
	}
	return 0
}

func (x *InfoStat) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InfoStat) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *InfoStat) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *InfoStat) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *InfoStat) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *InfoStat) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *InfoStat) GetVirtSystem() string {
	if x != nil {
		return x.VirtSystem
	}
	return ""
}

func (x *InfoStat) GetVirtRole() string {
	if x != nil {
		return x.VirtRole
	}
	return ""
}

func (x *InfoStat) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are assignable to Message:
	//	*Message_RegisterMessage
	//	*Message_PingMessage
	//	*Message_PongMessage
	//	*Message_EventMessage
	//	*Message_TriggerAllMessage
	//	*Message_RepeatRegistrationMessage
	//	*Message_MemberUpdateMessage
	Message isMessage_Message `protobuf_oneof:"message"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Message) GetRegisterMessage() *RegisterMessage {
	if x, ok := x.GetMessage().(*Message_RegisterMessage); ok {
		return x.RegisterMessage
	}
	return nil
}

func (x *Message) GetPingMessage() *PingMessage {
	if x, ok := x.GetMessage().(*Message_PingMessage); ok {
		return x.PingMessage
	}
	return nil
}

func (x *Message) GetPongMessage() *PongMessage {
	if x, ok := x.GetMessage().(*Message_PongMessage); ok {
		return x.PongMessage
	}
	return nil
}

func (x *Message) GetEventMessage() *EventMessage {
	if x, ok := x.GetMessage().(*Message_EventMessage); ok {
		return x.EventMessage
	}
	return nil
}

func (x *Message) GetTriggerAllMessage() *TriggerAllMessage {
	if x, ok := x.GetMessage().(*Message_TriggerAllMessage); ok {
		return x.TriggerAllMessage
	}
	return nil
}

func (x *Message) GetRepeatRegistrationMessage() *RepeatRegistrationMessage {
	if x, ok := x.GetMessage().(*Message_RepeatRegistrationMessage); ok {
		return x.RepeatRegistrationMessage
	}
	return nil
}

func (x *Message) GetMemberUpdateMessage() *MemberUpdateMessage {
	if x, ok := x.GetMessage().(*Message_MemberUpdateMessage); ok {
		return x.MemberUpdateMessage
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_RegisterMessage struct {
	RegisterMessage *RegisterMessage `protobuf:"bytes,100,opt,name=register_message,json=registerMessage,proto3,oneof"`
}

type Message_PingMessage struct {
	PingMessage *PingMessage `protobuf:"bytes,101,opt,name=ping_message,json=pingMessage,proto3,oneof"`
}

type Message_PongMessage struct {
	PongMessage *PongMessage `protobuf:"bytes,102,opt,name=pong_message,json=pongMessage,proto3,oneof"`
}

type Message_EventMessage struct {
	EventMessage *EventMessage `protobuf:"bytes,103,opt,name=event_message,json=eventMessage,proto3,oneof"`
}

type Message_TriggerAllMessage struct {
	TriggerAllMessage *TriggerAllMessage `protobuf:"bytes,104,opt,name=trigger_all_message,json=triggerAllMessage,proto3,oneof"`
}

type Message_RepeatRegistrationMessage struct {
	RepeatRegistrationMessage *RepeatRegistrationMessage `protobuf:"bytes,105,opt,name=repeat_registration_message,json=repeatRegistrationMessage,proto3,oneof"`
}

type Message_MemberUpdateMessage struct {
	MemberUpdateMessage *MemberUpdateMessage `protobuf:"bytes,106,opt,name=member_update_message,json=memberUpdateMessage,proto3,oneof"`
}

func (*Message_RegisterMessage) isMessage_Message() {}

func (*Message_PingMessage) isMessage_Message() {}

func (*Message_PongMessage) isMessage_Message() {}

func (*Message_EventMessage) isMessage_Message() {}

func (*Message_TriggerAllMessage) isMessage_Message() {}

func (*Message_RepeatRegistrationMessage) isMessage_Message() {}

func (*Message_MemberUpdateMessage) isMessage_Message() {}

type RegisterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterMessage) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamId string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Ts       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{9}
}

func (x *PingMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PingMessage) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *PingMessage) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type PongMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamId string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Ts       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{10}
}

func (x *PongMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PongMessage) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *PongMessage) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type TriggerAllMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TriggerAllMessage) Reset() {
	*x = TriggerAllMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerAllMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAllMessage) ProtoMessage() {}

func (x *TriggerAllMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAllMessage.ProtoReflect.Descriptor instead.
func (*TriggerAllMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerAllMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RepeatRegistrationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RepeatRegistrationMessage) Reset() {
	*x = RepeatRegistrationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatRegistrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatRegistrationMessage) ProtoMessage() {}

func (x *RepeatRegistrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatRegistrationMessage.ProtoReflect.Descriptor instead.
func (*RepeatRegistrationMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{12}
}

func (x *RepeatRegistrationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MemberUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *MemberUpdateMessage) Reset() {
	*x = MemberUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberUpdateMessage) ProtoMessage() {}

func (x *MemberUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberUpdateMessage.ProtoReflect.Descriptor instead.
func (*MemberUpdateMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{13}
}

func (x *MemberUpdateMessage) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type EventMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Type             CheckType              `protobuf:"varint,2,opt,name=type,proto3,enum=rsca.api.CheckType" json:"type,omitempty"`
	Check            string                 `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
	Status           Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=rsca.api.Status" json:"status,omitempty"`
	Output           string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	OutputError      string                 `protobuf:"bytes,10,opt,name=output_error,json=outputError,proto3" json:"output_error,omitempty"`
	Perfdata         string                 `protobuf:"bytes,6,opt,name=perfdata,proto3" json:"perfdata,omitempty"`
	RequestTimestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`
	Retries          int32                  `protobuf:"varint,8,opt,name=retries,proto3" json:"retries,omitempty"`
	Id               string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_rsca_api_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP(), []int{14}
}

func (x *EventMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EventMessage) GetType() CheckType {
	if x != nil {
		return x.Type
	}
	return CheckType_HOST
}

func (x *EventMessage) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *EventMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *EventMessage) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *EventMessage) GetOutputError() string {
	if x != nil {
		return x.OutputError
	}
	return ""
}

func (x *EventMessage) GetPerfdata() string {
	if x != nil {
		return x.Perfdata
	}
	return ""
}

func (x *EventMessage) GetRequestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTimestamp
	}
	return nil
}

func (x *EventMessage) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *EventMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_github_com_na4ma4_rsca_api_common_proto protoreflect.FileDescriptor

var file_github_com_na4ma4_rsca_api_common_proto_rawDesc = []byte{
	0x0a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x34,
	0x6d, 0x61, 0x34, 0x2f, 0x72, 0x73, 0x63, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x73, 0x63, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a,
	0x12, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x79, 0x0a,
	0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xd8, 0x04, 0x0a, 0x06, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x5a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x5b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65,
	0x6e, 0x12, 0x3c, 0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x30, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x18, 0xc8, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61,
	0x74, 0x12, 0x3e, 0x0a, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0xc9, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x40, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0xca, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e,
	0x5f, 0x61, 0x67, 0x6f, 0x18, 0xe9, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73,
	0x74, 0x53, 0x65, 0x65, 0x6e, 0x41, 0x67, 0x6f, 0x12, 0x19, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0xeb, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65,
	0x6e, 0x63, 0x79, 0x22, 0xca, 0x03, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x16, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x63, 0x73, 0x18, 0x18, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x63,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x1a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x27, 0x0a,
	0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6b, 0x65, 0x72, 0x6e, 0x65,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b,
	0x65, 0x72, 0x6e, 0x65, 0x6c, 0x41, 0x72, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69, 0x72,
	0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x76, 0x69, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x69,
	0x72, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x20, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76,
	0x69, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x22, 0xce, 0x04, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x46, 0x0a, 0x10,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x73, 0x63,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x6f, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0d,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x67, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a, 0x13, 0x74,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x11, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x65, 0x0a, 0x1b, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x69, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x19, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x53, 0x0a, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3b, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x66,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0x66, 0x0a, 0x0b, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0x23,
	0x0a, 0x11, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3f, 0x0a, 0x13, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x73, 0x63, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0xdd, 0x02, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x72,
	0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x28, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x72, 0x73, 0x63, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x66, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x66, 0x64, 0x61, 0x74, 0x61, 0x12, 0x47,
	0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x2a, 0x38, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x2a, 0x22, 0x0a, 0x09, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x42,
	0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61,
	0x34, 0x6d, 0x61, 0x34, 0x2f, 0x72, 0x73, 0x63, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_na4ma4_rsca_api_common_proto_rawDescOnce sync.Once
	file_github_com_na4ma4_rsca_api_common_proto_rawDescData = file_github_com_na4ma4_rsca_api_common_proto_rawDesc
)

func file_github_com_na4ma4_rsca_api_common_proto_rawDescGZIP() []byte {
	file_github_com_na4ma4_rsca_api_common_proto_rawDescOnce.Do(func() {
		file_github_com_na4ma4_rsca_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_na4ma4_rsca_api_common_proto_rawDescData)
	})
	return file_github_com_na4ma4_rsca_api_common_proto_rawDescData
}

var file_github_com_na4ma4_rsca_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_na4ma4_rsca_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_github_com_na4ma4_rsca_api_common_proto_goTypes = []interface{}{
	(Status)(0),                       // 0: rsca.api.Status
	(CheckType)(0),                    // 1: rsca.api.CheckType
	(*Empty)(nil),                     // 2: rsca.api.Empty
	(*TriggerAllResponse)(nil),        // 3: rsca.api.TriggerAllResponse
	(*TriggerInfoResponse)(nil),       // 4: rsca.api.TriggerInfoResponse
	(*Envelope)(nil),                  // 5: rsca.api.Envelope
	(*Members)(nil),                   // 6: rsca.api.Members
	(*Member)(nil),                    // 7: rsca.api.Member
	(*InfoStat)(nil),                  // 8: rsca.api.InfoStat
	(*Message)(nil),                   // 9: rsca.api.Message
	(*RegisterMessage)(nil),           // 10: rsca.api.RegisterMessage
	(*PingMessage)(nil),               // 11: rsca.api.PingMessage
	(*PongMessage)(nil),               // 12: rsca.api.PongMessage
	(*TriggerAllMessage)(nil),         // 13: rsca.api.TriggerAllMessage
	(*RepeatRegistrationMessage)(nil), // 14: rsca.api.RepeatRegistrationMessage
	(*MemberUpdateMessage)(nil),       // 15: rsca.api.MemberUpdateMessage
	(*EventMessage)(nil),              // 16: rsca.api.EventMessage
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 18: google.protobuf.Duration
}
var file_github_com_na4ma4_rsca_api_common_proto_depIdxs = []int32{
	7,  // 0: rsca.api.Envelope.sender:type_name -> rsca.api.Member
	6,  // 1: rsca.api.Envelope.recipient:type_name -> rsca.api.Members
	17, // 2: rsca.api.Member.last_seen:type_name -> google.protobuf.Timestamp
	18, // 3: rsca.api.Member.ping_latency:type_name -> google.protobuf.Duration
	8,  // 4: rsca.api.Member.info_stat:type_name -> rsca.api.InfoStat
	17, // 5: rsca.api.Member.system_start:type_name -> google.protobuf.Timestamp
	17, // 6: rsca.api.Member.process_start:type_name -> google.protobuf.Timestamp
	17, // 7: rsca.api.InfoStat.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 8: rsca.api.Message.envelope:type_name -> rsca.api.Envelope
	10, // 9: rsca.api.Message.register_message:type_name -> rsca.api.RegisterMessage
	11, // 10: rsca.api.Message.ping_message:type_name -> rsca.api.PingMessage
	12, // 11: rsca.api.Message.pong_message:type_name -> rsca.api.PongMessage
	16, // 12: rsca.api.Message.event_message:type_name -> rsca.api.EventMessage
	13, // 13: rsca.api.Message.trigger_all_message:type_name -> rsca.api.TriggerAllMessage
	14, // 14: rsca.api.Message.repeat_registration_message:type_name -> rsca.api.RepeatRegistrationMessage
	15, // 15: rsca.api.Message.member_update_message:type_name -> rsca.api.MemberUpdateMessage
	7,  // 16: rsca.api.RegisterMessage.member:type_name -> rsca.api.Member
	17, // 17: rsca.api.PingMessage.ts:type_name -> google.protobuf.Timestamp
	17, // 18: rsca.api.PongMessage.ts:type_name -> google.protobuf.Timestamp
	7,  // 19: rsca.api.MemberUpdateMessage.member:type_name -> rsca.api.Member
	1,  // 20: rsca.api.EventMessage.type:type_name -> rsca.api.CheckType
	0,  // 21: rsca.api.EventMessage.status:type_name -> rsca.api.Status
	17, // 22: rsca.api.EventMessage.request_timestamp:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_github_com_na4ma4_rsca_api_common_proto_init() }
func file_github_com_na4ma4_rsca_api_common_proto_init() {
	if File_github_com_na4ma4_rsca_api_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Members); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerAllMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatRegistrationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_na4ma4_rsca_api_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_na4ma4_rsca_api_common_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Message_RegisterMessage)(nil),
		(*Message_PingMessage)(nil),
		(*Message_PongMessage)(nil),
		(*Message_EventMessage)(nil),
		(*Message_TriggerAllMessage)(nil),
		(*Message_RepeatRegistrationMessage)(nil),
		(*Message_MemberUpdateMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_na4ma4_rsca_api_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_na4ma4_rsca_api_common_proto_goTypes,
		DependencyIndexes: file_github_com_na4ma4_rsca_api_common_proto_depIdxs,
		EnumInfos:         file_github_com_na4ma4_rsca_api_common_proto_enumTypes,
		MessageInfos:      file_github_com_na4ma4_rsca_api_common_proto_msgTypes,
	}.Build()
	File_github_com_na4ma4_rsca_api_common_proto = out.File
	file_github_com_na4ma4_rsca_api_common_proto_rawDesc = nil
	file_github_com_na4ma4_rsca_api_common_proto_goTypes = nil
	file_github_com_na4ma4_rsca_api_common_proto_depIdxs = nil
}
